[build]
builder = "nixpacks"
buildCommand = "yarn install --frozen-lockfile && yarn build"

[deploy]
startCommand = "yarn start"
healthcheckPath = "/api/_health"
restartPolicyType = "on_failure"

[nixpacks]
nodejs_version = "18"
install_command = "yarn install --frozen-lockfile"
plan = [
    { name = "install", command = "yarn install --frozen-lockfile" }
]