[build]
builder = "nixpacks"
buildCommand = "yarn install --frozen-lockfile && yarn build"

[deploy]
startCommand = "yarn start"
healthcheckPath = "/api/_health"
restartPolicyType = "on_failure"

[nixpacks]
nodejs_version = "20"
install_command = "yarn install --frozen-lockfile"